language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install scipy==1.2.1
  - pip install lifelines pytest>=3.6.0 pytest-cov>=2.6.1 codecov
  - python setup.py install
# command to run tests
script:
  - pytest --cov=maui/
after_success:
  - codecov
